---
# yamllint enable rule:key-ordering

# Please keep these lists sorted!
common:
    npm_pkgs:
        - eslint
        - html-differ
        - npm
        - pug-cli
        - tslint
        - typescript
        - vue-cli
    pip_pkgs:
        - ansible-lint
        - netaddr
        - pip
        - pre-commit
        - pylint
        - yamllint
        - yapf
darwin:
    brew_pkgs:
        - automake
        - bazel
        - byacc  # only used for building swig from source
        - cmake
        - ctags
        - curl
        - git
        - git-lfs
        - htop
        - iftop
        - jq
        - kubectl
        - libtool
        - node@10
        - pkg-config
        - python3
        - shellcheck
        - tree
        - wget
    cask_pkgs:
        - docker
        - google-cloud-sdk
        - visual-studio-code
debian:
    apt_pkgs:
        - automake
        - byacc  # only used for building swig from source
        - cmake
        - ctags
        - curl
        - git
        - htop
        - icedtea-netx  # for running java web applications
        - iftop
        - iotop
        - jq
        - libtool
        - openjdk-8-jdk
        - python3
        - python3-pip
        - shellcheck
        - ssh
        - tree
        - wget
    third_party:
        gpgs:
            # yamllint disable rule:line-length
            - https://apt.llvm.org/llvm-snapshot.gpg.key
            - https://bazel.build/bazel-release.pub.gpg
            - https://deb.nodesource.com/gpgkey/nodesource.gpg.key
            - https://download.docker.com/linux/ubuntu/gpg
            - https://packagecloud.io/github/git-lfs/gpgkey
            #- https://packages.cloud.google.com/apt/doc/apt-key.gpg
            - https://packages.microsoft.com/keys/microsoft.asc
            # yamllint enable rule:line-length
        pkgs:
            #- bazel
            - code
            - docker-ce
            - git-lfs
            #- kubectl
            - nodejs
            # The clang-* pacakges are tested to be installable and working.
            # However, I still want to use the installation at /opt/clang for
            # now.  Leave these as comments so that in the future it is easy to
            # switch to installing from ppa.
            #- clang-6.0
            #- clang-format-6.0
            #- clang-tidy-6.0
        repos:
            # yamllint disable rule:line-length
            - "deb http://apt.llvm.org/{{ ansible_distribution_release }}/ llvm-toolchain-{{ ansible_distribution_release }}-6.0 main"
            - "deb http://apt.kubernetes.io/ kubernetes-{{ ansible_distribution_release }} main"
            - "deb http://storage.googleapis.com/bazel-apt stable jdk1.8"
            - "deb https://deb.nodesource.com/node_10.x {{ ansible_distribution_release }} main"
            - "deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
            - "deb https://packagecloud.io/github/git-lfs/ubuntu/ {{ ansible_distribution_release }} main"
            - "deb https://packages.microsoft.com/repos/vscode stable main"
            # yamllint enable rule:line-length
    unused_pkgs:
        - astyle
        - cscope
        - ctags
        - debconf-utils
        - genisoimage
        - libguestfs-tools
        - libvirt-bin
        - mdadm
        - mongodb
        - qemu-system-x86
        - smartmontools
        - squashfs-tools
        - syslinux-utils # for isohybrid
        - twine # for uploading python packages to pypi
        - virt-manager
