---

- name: add gpg key for third party apt-repos
  become: true
  apt_key:
      url: "{{ item }}"
      state: present
  with_items:
      - https://bazel.build/bazel-release.pub.gpg
      - https://deb.nodesource.com/gpgkey/nodesource.gpg.key
      - https://download.docker.com/linux/ubuntu/gpg
      - https://packagecloud.io/github/git-lfs/gpgkey
      - https://packages.microsoft.com/keys/microsoft.asc

- name: add third party apt-repos
  become: true
  apt_repository:
      repo: "{{ item }}"
      state: present
  with_items:
      # yamllint disable rule:line-length
      - "deb http://storage.googleapis.com/bazel-apt stable jdk1.8"
      - "deb https://deb.nodesource.com/node_8.x {{ ansible_distribution_release }} main"
      - "deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
      - "deb https://packagecloud.io/github/git-lfs/ubuntu/ {{ ansible_distribution_release }} main"
      - "deb https://packages.microsoft.com/repos/vscode stable main"
      # yamllint enable rule:line-length

- name: apt update
  become: true
  apt:
      update_cache: true

- name: install third party packages
  become: true
  apt:
      pkg: "{{ item }}"
      state: latest
  with_items:
      - bazel
      - code
      - docker-ce
      - git-lfs
      - nodejs

- name: configure npm source
  become: true
  command: npm config set registry https://registry.npmjs.org/

- name: configure pypi source
  file:
      path: "{{ lookup('env', 'HOME') }}/.pip/pip.conf"
      state: absent
