---

- name: add gpg key for third party apt-repos
  become: true
  apt_key:
      url: "{{ item }}"
      state: present
  with_items: "{{ debian.third_party.gpgs }}"

- name: add third party apt-repos
  become: true
  apt_repository:
      repo: "{{ item }}"
      state: present
  with_items: "{{ debian.third_party.repos }}"

- name: apt update
  become: true
  apt:
      update_cache: true

- name: install third party packages
  become: true
  apt:
      pkg: "{{ item }}"
      state: latest
  with_items: "{{ debian.third_party.pkgs }}"

- name: configure npm source
  become: true
  command: npm config set registry https://registry.npmjs.org/

- name: configure pypi source
  file:
      path: "{{ lookup('env', 'HOME') }}/.pip/pip.conf"
      state: absent
