---

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v1.2.3
      hooks:
          - id: end-of-file-fixer
          - id: trailing-whitespace
          - id: name-tests-test

    # Use local hooks to ensure correct configuration.
    # TODO (zhongming): Eventually migrate to remote linters when the
    # technologies mature.  Using local hooks adds burden to the host
    # environment setup.
    - repo: local
      hooks:
          # Lint bash scripts.
          #
          # Bash is the only supported shell.  Everything is tuned to work with
          # bash.  They may still work to some extent with other shells.  But
          # use at your own peril!
          #
          # On macos, shellcheck is installed via:
          #       brew install shellcheck
          #
          # For more information, see:
          #       https://github.com/koalaman/shellcheck
          - id: shellcheck
            name: shellcheck (shell scripts)
            entry: shellcheck --shell=bash
            language: system
            types: [bash]

          # Lint plain yaml files.
          #
          # See more information at:
          #     https://github.com/adrienverge/yamllint
          #
          # This linter lints both .yaml and .yml files.  .yml files are ansible
          # scripts by convention and are linted by ansible-lint again.
          #
          # If you want to disable specific checks in a file or for a line,
          # consult the page below:
          # yamllint disable-line rule:line-length
          #     http://yamllint.readthedocs.io/en/stable/disable_with_comments.html#
          - id: yamllint
            name: yamllint (lint yaml files)
            entry: yamllint -c .yamllint.yaml
            language: system
            types: [yaml]

          # Lint ansible scripts.
          #
          # More information about the linter:
          #       https://github.com/willthames/ansible-lint
          #
          # By convention, ansible yaml scripts have .yml extension name,
          # whereas regular yaml files have the .yaml extension name.
          #
          # Note that ansible scripts, i.e., .yml files, are linted twice.  Once
          # by yamllint, then by ansible-lint.
          - id: ansible-lint
            name: ansible-lint (lint ansible .yml files)
            entry: ansible-lint --force-color -c .ansible-lint
            language: system
            files: \.yml$
