---

# The default configuration can be retrieved here:
#       https://yamllint.readthedocs.io/en/stable/configuration.html
#
# The rules are thoroughly explained with examples here:
#       https://yamllint.readthedocs.io/en/stable/rules.html
extends: default

rules:
    comments:
        require-starting-space: false
    indentation:
        spaces: 4
