---

- name: update homebrew and upgrade packages
  homebrew:
      update_homebrew: true
      upgrade_all: true

- name: homebrew install standard packages
  homebrew:
      name: "{{ item }}"
      state: upgraded
  with_items: "{{ darwin.brew_pkgs }}"

- name: install homebrew cask pacakges
  homebrew_cask:
      name: "{{ item }}"
      state: upgraded
  with_items: "{{ darwin.cask_pkgs }}"

- name: start docker daemon
  shell: open /Applications/Docker.app

- name: install python3 pacakges via pip3
  pip:
      name: "{{ item }}"
      state: latest
      executable: pip3
  with_items: "{{ common.pip_pkgs }}"

- name: npm install -g packages
  npm:
      executable: npm
      global: true
      name: "{{ item }}"
      state: latest
  with_items: "{{ common.npm_pkgs }}"
