---

- name: uninstall i386 packages
  become: true
  command: "apt purge \".*:i386\""
  args:
      warn: false
  # If there is no i386 packages installed at all, this task will report error.
  # But that is OK.
  ignore_errors: true

- name: completely remove i386
  become: true
  command: dpkg --remove-architecture i386

- name: install essential developer tools
  become: true
  apt:
      pkg: "{{ item }}"
      state: latest
  with_items: "{{ debian.apt_pkgs }}"

- name: add gpg key for third party apt-repos
  become: true
  apt_key:
      file: "{{ item }}"
      state: present
  with_fileglob: "{{ role_path }}/files/gpg/*"

- name: remove /etc/apt/sources.list.d/*
  become: true
  file:
      path: /etc/apt/sources.list.d
      state: absent

- name: apt update
  become: true
  apt:
      update_cache: true

- name: install third party packages
  become: true
  apt:
      pkg: "{{ item }}"
      state: latest
  with_items: "{{ debian.third_party.pkgs }}"

- name: install python3 pacakges via pip3
  become: true
  pip:
      name: "{{ item }}"
      state: latest
      executable: pip3
  with_items: "{{ common.pip_pkgs }}"

# This task will take effect after a reboot.
- name: add current user to group docker
  become: true
  user:
      name: "{{ ansible_user_id }}"
      groups: docker
      append: true

- name: npm install -g packages
  become: true
  npm:
      executable: npm
      global: true
      name: "{{ item }}"
      state: latest
  with_items: "{{ common.npm_pkgs }}"
