---

- name: install gnome
  become: yes
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items:
    - gnome-shell
    - ubuntu-gnome-desktop

- name: use lightdm as the graphical windows manager
  become: yes
  debconf:
    name: "{{ item }}"
    question: shared/default-x-display-manager
    value: lightdm
    vtype: select
  with_items:
    - gdm3
    - lightdm
  notify:
    - restart-lightdm

- name: customize greeter ui
  become: yes
  copy:
    src: 50-ubuntu.conf
    dest: /usr/share/lightdm/lightdm.conf.d/50-ubuntu.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart-lightdm

- name: flush_handlers
  meta: flush_handlers
