---

- name: install mongo
  apt: pkg=mongo state=latest update_cache=yes

- name: pip3 install pymongo
  become: yes
  become_user: root
  pip: name=pymongo state=latest update=yes executable=pip3

- name: become unpreveliged user
  become: no
  command: /bin/true
