---

- name: mkdir ~/.bashrc.d
  file:
      path: "{{ lookup('env','HOME') }}/.bashrc.d/{{ item }}"
      state: directory
  with_items:
      - alias.d
      - completion.d
      - env.d
      - function.d
      - prompt.d

- name: install ~/.bashrc.d/**
  synchronize:
      src: .bashrc.d
      dest: "{{ lookup('env','HOME') }}/"
      recursive: true
      delete: true

- name: install ~/.bashrc_main
  copy:
      src: bashrc_main
      dest: "{{ lookup('env','HOME') }}/.bashrc_main"

- include_tasks: "{{ ansible_os_family }}.yml"
