---

- name: install prerequisites for building tensorflow from source
  become: true
  apt:
      pkg: "{{ item }}"
      state: latest
  with_items:
      - python3-dev
      - python3-numpy
      - python3-pip
      - python3-wheel
      - libcupti-dev

- name: pip install packages
  become: true
  pip:
      executable: pip3
      name: "{{ item }}"
  with_items:
      # For running ipython notebooks
      - ipython
      - jupyter
      # For Udacity deep learning class
      - imageio
      - matplotlib
      - numpy
      - scipy
      - sklearn
