---
- name: install homebrew if not installed
  shell: >
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  ignore_errors: yes

- name: update homebrew and upgrade packages
  shell: brew update && brew upgrade

- name: homebrew install standard packages
  homebrew: name="{{ item }}" state=present
  with_items:
    - astyle
    - ctags
    - jq
    - pkg-config
    - python
    - python3
    - tree
    - wget

# Ansible does not have very good support for casks and taps yet.  Fine.
- name: homebrew install from custom taps
  shell: "{{ item }}"
  with_items:
    - brew cask install docker
    #- brew tap burntsushi/ripgrep https://github.com/BurntSushi/ripgrep.git \
            #&& brew install burntsushi/ripgrep/ripgrep-bin
  ignore_errors: yes
