---

- name: update homebrew and upgrade packages
  homebrew:
    update_homebrew: yes
    upgrade_all: yes

- name: homebrew install standard packages
  homebrew: name="{{ item }}" state=present
  with_items:
    - astyle
    - ctags
    - jq
    - pkg-config
    - python
    - python3
    - tree
    - wget

- name: install and start docker
  shell: "{{ item }}"
  with_items:
    - brew cask install docker
    - open /Applications/Docker.app
