alias ipmi="ipmitool -I lanplus -U ADMIN -P ADMIN -H"
alias ipmi-sol="ipmitool -I lanplus -U ADMIN -P ADMIN sol activate -H"
alias ipmi-status="ipmitool -I lanplus -U ADMIN -P ADMIN power status -H"
alias ipmi-up="ipmitool -I lanplus -U ADMIN -P ADMIN power up -H"
alias ipmi-down="ipmitool -I lanplus -U ADMIN -P ADMIN power down -H"
alias ipmi-reset="ipmitool -I lanplus -U ADMIN -P ADMIN power reset -H"
