---

- name: detect existing installation
  stat:
    path: /opt/clang/5.0.1/bin
  register: clang_bin_stat

- name: download prebuilt clang tarball
  get_url:
    url: http://releases.llvm.org/5.0.1/clang+llvm-5.0.1-x86_64-linux-gnu-ubuntu-16.04.tar.xz
    dest: /tmp/_ansible_clang.tar.xz
  when: clang_bin_stat.stat is defined and not clang_bin_stat.stat.isdir

# This may take around 10 minutes.
- name: extract to a temporary directory
  unarchive:
    src: /tmp/_ansible_clang.tar.xz
    dest: /tmp
  when: clang_bin_stat.stat is defined and not clang_bin_stat.stat.isdir

- name: create the install directory
  become: yes
  file:
    path: /opt/clang
    state: directory
    mode: 0755
    owner: root
    group: root
  when: clang_bin_stat.stat is defined and not clang_bin_stat.stat.isdir

- name: copy to the install directory
  become: yes
  synchronize:
    # Don't remove the trailing slash in src.  Without the trailing slash, you
    # end up with /opt/clang/5.0.1/clang+llvm-5.0.1-x86_64-linux-gnu-ubuntu-16.04.
    src: /tmp/clang+llvm-5.0.1-x86_64-linux-gnu-ubuntu-16.04/
    dest: /opt/clang/5.0.1
    delete: yes
    recursive: yes
    rsync_opts:
      - "--owner=root:root"
  when: clang_bin_stat.stat is defined and not clang_bin_stat.stat.isdir

- name: Add proper paths to PATH and LD_LIBEARY_PATH
  copy:
    src: clang.sh
    dest: "{{ lookup('env', 'HOME') }}/.bashrc.d/env.d/clang.sh "
