---

- include_tasks: "{{ ansible_os_family }}.yml"

- name: install ~/.git{config,ignore}
  copy:
      src: "{{ role_path }}/files/{{ item }}"
      dest: "{{ lookup('env', 'HOME') }}/.{{ item }}"
  with_items:
      - gitconfig
      - gitignore

- name: install ~/.gitignore
  copy:
      src: gitignore
      dest: "{{ lookup('env', 'HOME') }}/.gitignore"

- name: git clone bash-git-prompt
  git:
      repo: https://github.com/magicmonty/bash-git-prompt.git
      dest: "{{ lookup('env', 'HOME') }}/.bash-git-prompt"
      clone: true
      update: true
  tags:
      skip_ansible_lint
