---

- name: (Darwin only) update homebrew and upgrade packages
  shell: brew update && brew upgrade
  when: ansible_os_family == "Darwin"

- name: (Darwin only) install {git,wget} with homebrew
  homebrew: name={{ item }} state=present
  when: ansible_os_family == "Darwin"
  with_items:
    - git

- name: (Ubuntu only) install git with apt-get
  apt: pkg=git state=latest update_cache=yes
  when: ansible_os_family == "Ubuntu"

- name: install ~/.gitconfig
  copy:
    src=gitconfig
    dest="{{ lookup('env','HOME') }}/.gitconfig"

- name: install ~/.gitignore_global
  copy:
    src=gitignore_global
    dest="{{ lookup('env','HOME') }}/.gitignore_global"

- name: download git-completion.bash git-prompt.sh
  uri:
    url="https://raw.githubusercontent.com/git/git/master/contrib/completion/{{ item.0 }}"
    dest="{{ lookup('env','HOME') }}/.bashrc.d/{{ item.1 }}"
  with_items:
    - [ [ 'git-completion.bash', 'completion.d/git-completion.bash' ] ]
    - [ [ 'git-prompt.sh', 'prompt.d/git-prompt.sh' ] ]
