---

- name: (Darwin only) install macvim with python3 and lua support
  homebrew: >
    name=macvim
    state=present
    install_options="--with-python3 --with-lua"
  when: ansible_os_family == "Darwin"

- name: (Ubuntu only) install gvim
  apt:
    pkg=vim-gnome
    state=latest
    update_cache=yes
  when: ansible_os_family == "Ubuntu"

- name: mkdir ~/.vim
  file: >
    path="{{ lookup('env','HOME') }}/.vim"
    state=absent

- name: install pathogen
  shell: >
    mkdir -p ~/.vim/autoload ~/.vim/bundle &&
    curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim

- name: install vimrc
  copy: >
    src=vimrc
    dest="{{ lookup('env','HOME') }}/.vimrc"
    force=yes

- name: install vim plugins
  git:
    repo="{{ item.0 }}"
    dest="{{ lookup('env','HOME') }}/.vim/bundle/{{ item.1 }}"
    clone=yes
    update=yes
  with_items:
    - [ [ 'https://github.com/vim-scripts/taglist.vim', 'taglist.vim' ] ]
    - [ [ 'https://github.com/scrooloose/nerdtree', 'nerdtree' ] ]
    - [ [ 'https://github.com/scrooloose/nerdcommenter', 'nerdcommenter' ] ]
    - [ [ 'https://github.com/Shougo/neocomplete.vim', 'neocomplete.vim' ] ]
    - [ [ 'https://github.com/Shougo/neosnippet.vim', 'neosnippet.vim' ] ]
    - [ [ 'https://github.com/Shougo/neosnippet-snippets', 'neosnippet-snippets' ] ]
    - [ [ 'https://github.com/Lokaltog/vim-easymotion', 'vim-easymotion' ] ]
    - [ [ 'https://github.com/kien/ctrlp.vim', 'ctrlp.vim' ] ]
    - [ [ 'https://github.com/justinmk/vim-syntax-extra', 'vim-syntax-extra' ] ]
    - [ [ 'https://github.com/xolox/vim-misc', 'vim-misc' ] ]
    - [ [ 'https://github.com/flazz/vim-colorschemes', 'vim-colorschemes' ] ]
    - [ [ 'https://github.com/ntpeters/vim-better-whitespace', 'vim-better-whitespace' ] ]
    - [ [ 'https://github.com/elzr/vim-json', 'vim-json' ] ]
    - [ [ 'https://github.com/peterhoeg/vim-qml', 'vim-qml' ] ]
    - [ [ 'https://github.com/wannesm/wmgraphviz.vim', 'wmgraphviz.vim' ] ]
    - [ [ 'https://github.com/autowitch/hive.vim', 'hive.vim' ] ]
    - [ [ 'https://github.com/tpope/vim-unimpaired', 'vim-unimpaired' ] ]
    - [ [ 'https://github.com/kshenoy/vim-signature', 'vim-signature' ] ]
    - [ [ 'https://github.com/tfnico/vim-gradle', 'vim-gradle' ] ]
    - [ [ 'https://github.com/pearofducks/ansible-vim', 'ansible-vim' ] ]
    - [ [ 'https://github.com/fatih/vim-go', 'vim-go' ] ]
    - [ [ 'https://github.com/tpope/vim-fugitive', 'vim-fugitive' ] ]
