---

vim:
    plugins:
        # yamllint disable rule:line-length
        'Smyck-Color-Scheme': 'https://github.com/hukl/Smyck-Color-Scheme'
        'ansible-vim': 'https://github.com/pearofducks/ansible-vim'
        'ctrlp.vim': 'https://github.com/kien/ctrlp.vim'
        'hive.vim': 'https://github.com/autowitch/hive.vim'
        'neocomplete.vim': 'https://github.com/Shougo/neocomplete.vim'
        'neosnippet-snippets': 'https://github.com/Shougo/neosnippet-snippets'
        'neosnippet.vim': 'https://github.com/Shougo/neosnippet.vim'
        'nerdcommenter': 'https://github.com/scrooloose/nerdcommenter'
        'nerdtree': 'https://github.com/scrooloose/nerdtree'
        'taglist.vim': 'https://github.com/vim-scripts/taglist.vim'
        'typescript-vim': 'https://github.com/leafgarland/typescript-vim'
        'vim-better-whitespace': 'https://github.com/ntpeters/vim-better-whitespace'
        'vim-colorschemes': 'https://github.com/flazz/vim-colorschemes'
        'vim-easymotion': 'https://github.com/Lokaltog/vim-easymotion'
        'vim-fugitive': 'https://github.com/tpope/vim-fugitive'
        'vim-go': 'https://github.com/fatih/vim-go'
        'vim-gradle': 'https://github.com/tfnico/vim-gradle'
        'vim-json': 'https://github.com/elzr/vim-json'
        'vim-misc': 'https://github.com/xolox/vim-misc'
        'vim-numbertoggle': 'https://github.com/jeffkreeftmeijer/vim-numbertoggle'
        'vim-qml': 'https://github.com/peterhoeg/vim-qml'
        'vim-signature': 'https://github.com/kshenoy/vim-signature'
        'vim-swift': 'https://github.com/kballard/vim-swift'
        'vim-syntax-extra': 'https://github.com/justinmk/vim-syntax-extra'
        'vim-unimpaired': 'https://github.com/tpope/vim-unimpaired'
        'wmgraphviz.vim': 'https://github.com/wannesm/wmgraphviz.vim'
        # yamllint enable rule:line-length
