---

- name: install packages
  apt: pkg={{ item }} state=latest update_cache=yes
  become: yes
  with_items:
    - git
    - python-pip
    - python3-pip
    - twine # for uploading python packages to pypi
    - ctags
