---

- name: dpkg remove i386
  become: yes
  command: dpkg --remove-architecture i386

- name: install packages
  apt: pkg={{ item }} state=latest update_cache=yes
  become: yes
  with_items:
    - git
    - python-pip
    - python3-pip
    - ssh
