---

- include_tasks: "{{ ansible_os_family }}.yml"

# The following two tasks are just a transcription of the command below:
#   mkdir -p ~/.vim/autoload ~/.vim/bundle &&
#   curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim
- name: create vim directories
  file:
      path: "{{ lookup('env','HOME') }}/.vim/{{ item }}"
      state: directory
  with_items:
      - autoload
      - bundle

- name: install pathogen
  get_url:
      url: https://tpo.pe/pathogen.vim
      dest: "{{ lookup('env','HOME') }}/.vim/autoload/pathogen.vim"

- name: install vimrc
  copy:
      src: vimrc
      dest: "{{ lookup('env','HOME') }}/.vimrc"
      force: true

- name: install vim plugins
  git:
      repo: "{{ item.value }}"
      dest: "{{ lookup('env','HOME') }}/.vim/bundle/{{ item.key }}"
      clone: true
      update: true
      force: true
  tags:
      - skip_ansible_lint
  with_dict:
      # yamllint disable rule:line-length
      'Smyck-Color-Scheme': 'https://github.com/hukl/Smyck-Color-Scheme'
      'ansible-vim': 'https://github.com/pearofducks/ansible-vim'
      'ctrlp.vim': 'https://github.com/kien/ctrlp.vim'
      'hive.vim': 'https://github.com/autowitch/hive.vim'
      'neocomplete.vim': 'https://github.com/Shougo/neocomplete.vim'
      'neosnippet-snippets': 'https://github.com/Shougo/neosnippet-snippets'
      'neosnippet.vim': 'https://github.com/Shougo/neosnippet.vim'
      'nerdcommenter': 'https://github.com/scrooloose/nerdcommenter'
      'nerdtree': 'https://github.com/scrooloose/nerdtree'
      'taglist.vim': 'https://github.com/vim-scripts/taglist.vim'
      'vim-better-whitespace': 'https://github.com/ntpeters/vim-better-whitespace'
      'vim-colorschemes': 'https://github.com/flazz/vim-colorschemes'
      'vim-easymotion': 'https://github.com/Lokaltog/vim-easymotion'
      'vim-fugitive': 'https://github.com/tpope/vim-fugitive'
      'vim-go': 'https://github.com/fatih/vim-go'
      'vim-gradle': 'https://github.com/tfnico/vim-gradle'
      'vim-json': 'https://github.com/elzr/vim-json'
      'vim-misc': 'https://github.com/xolox/vim-misc'
      'vim-numbertoggle': 'https://github.com/jeffkreeftmeijer/vim-numbertoggle.git'
      'vim-qml': 'https://github.com/peterhoeg/vim-qml'
      'vim-signature': 'https://github.com/kshenoy/vim-signature'
      'vim-swift': 'https://github.com/kballard/vim-swift.git'
      'vim-syntax-extra': 'https://github.com/justinmk/vim-syntax-extra'
      'vim-unimpaired': 'https://github.com/tpope/vim-unimpaired'
      'wmgraphviz.vim': 'https://github.com/wannesm/wmgraphviz.vim'
      # yamllint enable rule:line-length
