---

- include_tasks: "{{ ansible_os_family }}.yml"

# The following two tasks are just a transcription of the command below:
#   mkdir -p ~/.vim/autoload ~/.vim/bundle &&
#   curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim
- name: create vim directories
  file:
      path: "{{ lookup('env','HOME') }}/.vim/{{ item }}"
      state: directory
  with_items:
      - autoload
      - bundle

- name: install pathogen
  get_url:
      url: https://tpo.pe/pathogen.vim
      dest: "{{ lookup('env','HOME') }}/.vim/autoload/pathogen.vim"

- name: install vimrc
  copy:
      src: vimrc
      dest: "{{ lookup('env','HOME') }}/.vimrc"
      force: true

- name: install vim plugins
  git:
      repo: "{{ item.value }}"
      dest: "{{ lookup('env','HOME') }}/.vim/bundle/{{ item.key }}"
      clone: true
      update: true
      force: true
  tags:
      - skip_ansible_lint
  with_dict: "{{ vim.plugins }}"
