---

- name: dpkg remove i386
  become: yes
  command: dpkg --remove-architecture i386

- name: update apt-cache
  become: yes
  apt:
    update_cache: yes

- name: install common developer tools
  become: yes
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items:
    - cscope
    - ctags
    - debconf-utils
    - docker.io
    - genisoimage
    - git
    - htop
    - iftop
    - iotop
    - syslinux-utils # for isohybrid
    - libguestfs-tools
    - libvirt-bin
    - mdadm
    - mongodb
    - python-pip
    - python3-pip
    - python3-libvirt
    - python3-paramiko
    - python3-yaml
    - qemu-system-x86
    - smartmontools
    - squashfs-tools
    - ssh
    - tree
    - twine # for uploading python packages to pypi
    - virt-manager

# This task will take effect after a reboot.
- name: add current user to group docker
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes

- name: install python3 packages that are only available via pip
  become: yes
  pip:
    name: "{{ item }}"
    state: latest
    executable: pip3
  with_items:
    - pymongo

# The libvirt has a feature called dynamic_ownership that causes libvirtd to
# change the ownership of disk images to root:root every time the containing
# libvirt domain is started.  That conflicts with the use model where non-root
# users can freely use libvirt domains.  As a result, turn dynamic_ownership off
# here.
- name: disable dynamic_ownership for libvirt
  become: yes
  lineinfile:
    dest: /etc/libvirt/qemu.conf
    regexp: "^dynamic_ownership(?! = 0)"
    line: "dynamic_ownership = 0"
    state: present
    backrefs: yes # if no match, do not change the file
  notify: restart-libvirt

- name: add gpg key for third party apt-repos
  become: yes
  apt_key:
    url: "{{ item }}"
    state: present
  with_items:
    - https://bazel.build/bazel-release.pub.gpg
    - https://packages.cloud.google.com/apt/doc/apt-key.gpg
    #- http://apt.llvm.org/llvm-snapshot.gpg.key

- name: add third party apt-repos
  become: yes
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - deb http://storage.googleapis.com/bazel-apt stable jdk1.8
    - "deb http://packages.cloud.google.com/apt cloud-sdk-{{ ansible_distribution_release }} main"
    #- deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-5.0 main

- name: apt-get update
  become: yes
  apt:
    update_cache: yes

- name: install various packages that are only available from third party apt repos
  become: yes
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items:
    - openjdk-8-jdk
    - bazel
    - google-cloud-sdk
    #- clang-5.0
    #- lldb-5.0
    #- lld-5.0


- name: flush_handlers
  meta: flush_handlers
