---

- name: print ansible_os_family
  debug: msg="{{ ansible_os_family }}"

- name: mkdir ~/.bashrc.d
  file: >
    path="{{ lookup('env','HOME') }}/.bashrc.d/{{ item }}"
    state=directory
  with_items:
    - alias.d
    - completion.d
    - env.d
    - function.d
    - prompt.d

- name: install ~/.bashrc.d/**
  synchronize: >
    src=.bashrc.d
    dest="{{ lookup('env','HOME') }}/"
    recursive=yes

- include: Darwin/setup-bashrc.yml
  when: ansible_os_family == "Darwin"

- include: Debian/setup-bashrc.yml
  when: ansible_os_family == "Debian"
