---

- name: mkdir -p ~/.bashrc.d/completion.d
  file: >
    path="{{ lookup('env','HOME') }}/.bashrc.d/completion.d"
    state=directory

- name: install ~/.bashrc.d/**
  synchronize: >
    src=.bashrc.d
    dest="{{ lookup('env','HOME') }}/"
    recursive=yes

- name: (Darwin only) ~/.bash_profile sources ~/.bashrc_main
  lineinfile: >
    dest="{{ lookup('env','HOME') }}/.bash_profile"
    line="[ -f ~/.bashrc_main ] && ~/.bashrc_main"
  when: ansible_os_family == "Darwin"

- name: (Ubuntu only) ~/.bash_profile sources ~/.bashrc
  lineinfile: >
    dest="{{ lookup('env','HOME') }}/.bash_profile"
    line="[ -f ~/.bashrc ] && ~/.bashrc"
  when: ansible_os_family == "Ubuntu"

- name: (Ubuntu only) ~/.bashrc sources ~/.bashrc_main
  lineinfile: >
    dest="{{ lookup('env','HOME') }}/.bashrc"
    line="[ -f ~/.bashrc_main ] && ~/.bashrc_main"
  when: ansible_os_family == "Ubuntu"
