---

# As of 0/13/2016, swift released a ubuntu apt repo.
# This playbook is written per the instructions here:
#     http://dev.iachieved.it/iachievedit/introducing-swift-3-0
# TODO: A few tasks could be made more ansible-like.

- name: add the repository key
  become: yes
  apt_key:
    url: http://dev.iachieved.it/iachievedit.gpg.key
    state: present

- name: add repository to sources.list
  become: yes
  apt_repository:
    repo: deb http://iachievedit-repos.s3.amazonaws.com/ xenial main
    state: present

- name: apt-get update
  become: yes
  apt:
    update_cache: yes

- name: install swift-3.0
  become: yes
  apt: pkg=swift-3.0 state=latest

- name: add swift path to bashrc
  lineinfile:
    dest: "{{ lookup('env','HOME') }}/.bashrc_main"
    state: present
    line: "export PATH=/opt/swift/swift-3.0/usr/bin:$PATH"
