---

- name: install prerequisite packages
  become: yes
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - libnl-3-dev
    - libnl-genl-3-dev

- name: install build-dep for aircrack-ng
  become: yes
  apt:
    name: aircrack-ng
    state: build-dep

- name: download aircrack-ng source code
  get_url:
    url: http://download.aircrack-ng.org/aircrack-ng-1.2-rc4.tar.gz
    dest: /tmp/aircrack-ng.tar.gz

- name: extract aircrack-ng source
  file:
    name: /tmp/aircrack-ng
    state: directory

- name: extract aircrack-ng source
  unarchive:
    src: /tmp/aircrack-ng.tar.gz
    dest: /tmp/aircrack-ng

# TODO: The 'make' module is only available from ansible 2.2.  Unfortunately,
# Ubuntu 16.04 only ships with ansible 2.0.  As a result, we keep these tasks so
# that when we upgrade to ansible 2.2, uncommenting the following suffices for
# installing aircrack.

#- name: build aircrack-ng with airolib-ng and pcre support
  #make:
    #chdir: /tmp/aircrack-ng
    #target: all
    #params:
      #sqlite=true
      #pcre=true

#- name: update the oui file
  #become: yes
  #command: airodump-ng-oui-update
